# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160523235928 on 2016-06-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librato_user', models.CharField(max_length=250)),
                ('librato_api_key', models.CharField(max_length=100)),
                ('recipients_emails', models.CharField(max_length=250)),
                ('chart_ids', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('template', models.CharField(max_length=100)),
            ],
        ),
    ]
