# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160523235928 on 2016-06-08 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librato_chart_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='chart_ids',
            field=models.CommaSeparatedIntegerField(max_length=250),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='recipients_emails',
            field=models.TextField(),
        ),
    ]
