# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librato_chart_sender', '0002_auto_20160608_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='template',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='interval',
            field=models.CharField(max_length=250),
        ),
    ]
